version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
