# Generated by Django 4.1.2 on 2022-10-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_warehouse_name2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouse",
            name="name2",
        ),
    ]
