# Generated by Django 4.1.2 on 2022-10-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0002_triptruck"),
        ("extraction_point", "0001_initial"),
        ("warehouse", "0003_remove_warehouse_name2"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseMoveMineralEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время события"
                    ),
                ),
                (
                    "total_tons",
                    models.FloatField(verbose_name="Масса всей выгрузки"),
                ),
                (
                    "si_o_2_tons",
                    models.FloatField(verbose_name="Масса диоксида кремния"),
                ),
                ("fe_tons", models.FloatField(verbose_name="Масса железа")),
                (
                    "extraction_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="extraction_point.extractionpoint",
                        verbose_name="Откуда привезли",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truck.truck",
                        verbose_name="Грузовик совершивший действие",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение по складу",
            },
        ),
        migrations.CreateModel(
            name="OutsideWarehouseMoveMineralEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время события"
                    ),
                ),
                (
                    "total_tons",
                    models.FloatField(verbose_name="Масса всей выгрузки"),
                ),
                (
                    "si_o_2_tons",
                    models.FloatField(verbose_name="Масса диоксида кремния"),
                ),
                ("fe_tons", models.FloatField(verbose_name="Масса железа")),
                (
                    "extraction_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="extraction_point.extractionpoint",
                        verbose_name="Откуда привезли",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truck.truck",
                        verbose_name="Грузовик совершивший действие",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отвалы промахи вокруг склада",
            },
        ),
    ]
