# Generated by Django 4.1.2 on 2022-10-24 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0003_alter_triptruck_truck"),
        ("warehouse", "0004_warehousemovemineralevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outsidewarehousemovemineralevent",
            name="truck",
        ),
        migrations.RemoveField(
            model_name="outsidewarehousemovemineralevent",
            name="warehouse",
        ),
        migrations.RemoveField(
            model_name="warehousemovemineralevent",
            name="truck",
        ),
        migrations.AddField(
            model_name="outsidewarehousemovemineralevent",
            name="trip_truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="truck.triptruck",
                verbose_name="Грузовик совершивший действие",
            ),
        ),
        migrations.AddField(
            model_name="warehousemovemineralevent",
            name="trip_truck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="truck.triptruck",
                verbose_name="Грузовик совершивший действие",
            ),
        ),
    ]
