# Generated by Django 4.1.2 on 2022-10-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Модель грузовика"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        verbose_name="Грузоподьемность тонн"
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель грузовика",
                "verbose_name_plural": "Модели грузовиков",
                "unique_together": {("name", "capacity")},
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Бортовой номер",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trucks",
                        to="truck.truckmodel",
                        verbose_name="Модель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Самосвал",
                "verbose_name_plural": "Самосвалы",
            },
        ),
    ]
