# Generated by Django 4.1.2 on 2022-10-24 11:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extraction_point", "0001_initial"),
        ("warehouse", "0003_remove_warehouse_name2"),
        ("truck", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complite",
                    models.BooleanField(
                        default=False,
                        verbose_name="Признак окончания поездки и опустошения кузова",
                    ),
                ),
                (
                    "weight_tons",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Сколько тон загружено",
                    ),
                ),
                (
                    "upload_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время погрузки"
                    ),
                ),
                (
                    "unload_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Координаты выгрузки",
                    ),
                ),
                (
                    "unload_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время выгрузки"
                    ),
                ),
                (
                    "extraction_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extraction_point.extractionpoint",
                        verbose_name="Точка загрузки",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="truck.truck",
                        verbose_name="Самосвал",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.warehouse",
                        verbose_name="Склад выгрузки",
                    ),
                ),
            ],
        ),
    ]
