# Generated by Django 4.1.2 on 2022-10-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extraction_point", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractionpoint",
            options={"verbose_name": "Точки загрузки руды"},
        ),
    ]
